name: Sync Fork
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: "sync-fork"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: delete sync-fork.yml
      run: rm -rf .github/workflows/sync-fork.yml
    - name: delete .git
      run: rm -rf .git
    - name: to target repo
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Sunwuyuan/zerocat-frontend.git
        BRANCH: main
        FOLDER: ./
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        #KNOWN_HOSTS_FILE: known_hosts
