name: Sync Fork
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: to target repo
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Sunwuyuan/zerocat-frontend.git
        BRANCH: main
        FOLDER: .
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        #KNOWN_HOSTS_FILE: known_hosts
